### ISSUE TITLE
Allow access to $contentfulEntries.includes

### ISSUE THREAD

**Issue by mismith** [jvandemo/angular-contentful#11]
I don't know if this is a new change on contentful's part or not, but I see in the response packet from, say, a call like this `https://cdn.contentful.com/spaces/XXX/entries?access_token=XXX&content_type=XXX` now returns an `includes` property alongside `items`, and it would be nice to be able to access that directly, in addition to continuing to auto-populate the linked _Resources_

Sample response:

```
{
  "sys": {
    "type": "Array"
  },
  "total": 1,
  "skip": 0,
  "limit": 100,
  "items": [
    {
      "sys": {…},
      "fields": {
        "title": "…",
        "downloads": [
          {
            "sys": {
              "type": "Link",
              "linkType": "Asset",
              "id": "…"
            }
          }
        ],
      }
    },
    …
  ],
  "includes": {
    "Asset": [
      {
        "sys": {…},
        "fields": {
          "file": {…},
          "title": "…"
        }
      },
      …
    ]
  }
}
```

**Comment by jvandemo** [comment]
@mismith &mdash; The `contentful-entries` directive automatically resolves linked resources if they are included in the `includes` key of the Contentful response.

Behind the scenes, the directive queries the Contentful API, walks over all the linked resources in the items and resolves them with the data from the `includes` if present.

So the heavy lifting is already done for you automatically and you should already have all information available in the `items` array.

Does that make sense? Thanks!

**Comment by mismith** [comment]
It totally does make sense and that's exactly what I figured it was doing, but I guess there must be some bug because this is failing for me using the latest (v2.0.0) build. I'll try to throw together a plunkr showing the problem when I get a sec.

**Comment by jvandemo** [comment]
@mismith &mdash; A plnkr would be very useful indeed. Thanks in advance!

**Comment by mismith** [comment]
Haha, I just spent 30 mins making a plunk before realizing that the code I was trying on Friday works this morning unchanged... I figured it must've been a bug in this library but now I'm leaning more towards some kind of service outtage on contentful's side? That would also explain why the Links were being pulled from the `includes` property sometimes but not others. Hopefully this doesn't happen again but if it does I've got a barebones plunk ready to go for figuring things further. Sorry to bug you!

**Comment by jvandemo** [comment]
@mismith &mdash; Thanks for the update.

No worries at all, feel free to re-open the issue if needed.

Have a great day!

**Comment by mismith** [comment]
Hmmm, it's happening again. Here's that plunk: http://plnkr.co/edit/Glk72SJH6Tn4ryqD58sp?p=preview

I notice that the raw response from contentful doesn't seem to include the `includes` property, but I'm not sure why not. Even explicitly calling `https://cdn.contentful.com/spaces/i117p4sejxck/entries/4ZpCW2HqcE046g6u0QwKSW?access_token=f91a6fa12aeecf1b2bf88151211eb2a5f8fccaf6ecf087ac61388bc8e0ccac63&include=1` doesn't seem to make a difference.

**Comment by jvandemo** [comment]
@mismith &mdash; Contentful does not include linked resources when querying for a single entry. It only includes linked resources when querying for multiple entries (even if only one entry is returned).

From the Contentful documentation:

_A reason to query an Entry by ID instead of retrieving the Entry itself might be because you want to include resolved links._

In terms of the Contentful API:
- [spaces/space-id/entries/entry-id](https://cdn.contentful.com/spaces/i117p4sejxck/entries/4ZpCW2HqcE046g6u0QwKSW?access_token=f91a6fa12aeecf1b2bf88151211eb2a5f8fccaf6ecf087ac61388bc8e0ccac63) does not include linked resources
- [spaces/space-id/entries?sys.id=entry-id](https://cdn.contentful.com/spaces/i117p4sejxck/entries?access_token=f91a6fa12aeecf1b2bf88151211eb2a5f8fccaf6ecf087ac61388bc8e0ccac63&sys.id=4ZpCW2HqcE046g6u0QwKSW) includes linked resources

In terms of this library
- `contentful-entry` will not include linked resources
- `contentful-entries` will include linked resources

As a workaround you can use the `contentful-entries` to only get one entry like this:

``` xml
<section contentful-entries="'sys.id=some-id'">
  {{ $contentfulEntries.items[0] }}
</section>
```

In essence it is caused by the way the Contentful API works and not by the inner workings of this library.

Does that explain the inconsistent behavior you are experiencing?

> I've used your space and access token in the links above, so make sure to remove the access token for security reasons.

**Comment by mismith** [comment]
That totally explains it; sorry for my oversight. Thanks for this awesome library.

**Comment by jvandemo** [comment]
@mismith &mdash; No problem, thank you for your feedback. Much appreciated!

**Comment by jvandemo** [comment]
A link to this issue has been added to the README in case other people are wondering why they experience similar behavior.
